### ISSUE TITLE
Add an endpoint to handle moodle oauth callback

### ISSUE THREAD

**Issue by martuto31** [rtrdxSka/UIS#11]
### Tasks

- [ ] Task 1: Create a controller that handles Moodle OAuth callback
- [x] Task 2: Reference Issue #8
- [x] Task 3: Reference Issue #9

### Acceptance Criteria

- Criterion 1: The code compiles
- Criterion 2: Implemented error handling
- Criterion 3: When a user authenticates, the API receives a code and a discord ID
- Criterion 4: Fetches user data successfully from the Moodle API
- Criterion 5: Saves the user data to a DB
