### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by rtrdxSka** [rtrdxSka/UIS#3]
### Tasks

- [x] Task 1: Create a file registerCommands
- [x] Task 2: make the bort accept the /auth command
- [x] Task 3: [register the commands to the bot]

### Acceptance Criteria

- Criterion 1: Compiles successfully
- Criterion 2: The bot can execute the /auth command
