### ISSUE TITLE
Create a simple UI for UIS to handle Moodle data updates

### ISSUE THREAD

**Issue by martuto31** [rtrdxSka/UIS#30]
### Tasks

- [x] Task 1: Create an endpoint that returns the data to be updated and the updated data.
- [x] Task 2: Create an endpoint that adds or deletes users from cohorts
- [x] Task 3: Create a simple UI

### Acceptance Criteria

- Criterion 1: The correct data is received and and adds or deletes users from cohorts successfully
