### ISSUE TITLE
Accept guildID through link and set role and guildid dynamically

### ISSUE THREAD

**Issue by rtrdxSka** [rtrdxSka/UIS#31]
### Tasks

- [x] Task 1: Get guildID through link
- [x] Task 2: Set guild dynamically 
- [ ] Task 3; Set role dynamically

### Acceptance Criteria

- Criterion 1: Code compiles
- Criterion 2: Getting correct guildID
- Criterion 3: Set role dynamically
