### ISSUE TITLE
Remove upper roles for discord users

### ISSUE THREAD

**Issue by rtrdxSka** [rtrdxSka/UIS#36]
### Tasks

- [x] Task 1: Remove upper roles from users
- [x] Task 2: keep lower roles
- [x] Task 3: set new role

### Acceptance Criteria

- Criterion 1: Code compiles
- Criterion 2: User has correct roles
