### ISSUE TITLE
Bot sends link with the discordId in it to the user

### ISSUE THREAD

**Issue by rtrdxSka** [rtrdxSka/UIS#5]
### Tasks

- [x] Task 1: The bot sends a link to the moodle login page when user types /auth
- [x] Task 2: Link must contain the discordID for the user
- [x] Task 3: The discordID must not be readable by the user (encrypted)

### Acceptance Criteria

- Criterion 1: Link is sent successfully
- Criterion 2: User can use link to login in moodle
