### ISSUE TITLE
User major and server 

### ISSUE THREAD

**Issue by rtrdxSka** [rtrdxSka/UIS#56]
### Tasks

- [x] Task 1: get major
- [x] Task 2: get server name 
- [ ] Task 3: check for match with DB
- [ ] Task 4: if match give role else take all roles

### Acceptance Criteria

- Criterion 1: Code compiles
- Criterion 2: Functionality works
