### ISSUE TITLE
Refactor HandleMoodleCallback endpoint

### ISSUE THREAD

**Issue by martuto31** [rtrdxSka/UIS#71]
### Tasks

- [ ] Task 1: Refactor the the callback
- [ ] Task 2: Fix bugs
- [ ] Task 3: Fix indents and typos

### Acceptance Criteria

- Criterion 1: The code compiles
